"""fix_subscription_tier_alias_and_add_pagination

Revision ID: d2d4919460f6
Revises: 9b5299a43259
Create Date: 2026-05-25 07:07:44.355439
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d4919460f6'
down_revision: Union[str, None] = '9b5299a43259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('sector', sa.String(length=10), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('balance_sheet_total', sa.Float(), nullable=True),
    sa.Column('csrd_wave', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('vat_number')
    )
    op.create_table('esrs_datapoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('standard_ref', sa.String(length=50), nullable=False),
    sa.Column('paragraph_ref', sa.String(length=50), nullable=True),
    sa.Column('disclosure_requirement', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_conditional', sa.Boolean(), nullable=False),
    sa.Column('phase_in_year', sa.Integer(), nullable=True),
    sa.Column('sfd_ref', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esrs_datapoints_standard_ref'), 'esrs_datapoints', ['standard_ref'], unique=False)
    op.create_table('regulatory_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regulation', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('affected_standards', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sustainability_matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('standard', sa.String(length=20), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('sub_topic', sa.String(length=255), nullable=True),
    sa.Column('sub_sub_topic', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sustainability_matters_standard'), 'sustainability_matters', ['standard'], unique=False)
    op.create_table('company_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('value_chain_description', sa.Text(), nullable=True),
    sa.Column('key_activities', sa.JSON(), nullable=True),
    sa.Column('business_relationships', sa.JSON(), nullable=True),
    sa.Column('geographical_scope', sa.JSON(), nullable=True),
    sa.Column('stakeholder_groups', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('emissions_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.Column('emission_factor_source', sa.String(length=50), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiality_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'audited', name='assessmentstatus'), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'final', 'filed', name='reportstatus'), nullable=False),
    sa.Column('xhtml_content', sa.Text(), nullable=True),
    sa.Column('xbrl_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', 'team', 'enterprise', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'contributor', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('materiality_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('datapoint_id', sa.UUID(), nullable=False),
    sa.Column('impact_scale', sa.Integer(), nullable=True),
    sa.Column('impact_scope', sa.Integer(), nullable=True),
    sa.Column('impact_irremediability', sa.Integer(), nullable=True),
    sa.Column('impact_likelihood', sa.Integer(), nullable=True),
    sa.Column('financial_magnitude', sa.Integer(), nullable=True),
    sa.Column('financial_likelihood', sa.Integer(), nullable=True),
    sa.Column('total_impact_score', sa.Float(), nullable=True),
    sa.Column('total_financial_score', sa.Float(), nullable=True),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['materiality_assessment.id'], ),
    sa.ForeignKeyConstraint(['datapoint_id'], ['esrs_datapoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materiality_scores')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('reports')
    op.drop_table('materiality_assessment')
    op.drop_table('emissions_data')
    op.drop_table('company_context')
    op.drop_index(op.f('ix_sustainability_matters_standard'), table_name='sustainability_matters')
    op.drop_table('sustainability_matters')
    op.drop_table('regulatory_updates')
    op.drop_index(op.f('ix_esrs_datapoints_standard_ref'), table_name='esrs_datapoints')
    op.drop_table('esrs_datapoints')
    op.drop_table('companies')
    # ### end Alembic commands ###
